# 第1章  机器学习基础

## 本章内容

* 机器学习简单概述
* 机器学习的主要任务
* 学习机器学习的原因
* Python语言的优势

## 1.1 何谓机器学习

简单点的说，**机器学习**就是把无序的数据转换为有用的信息。**机器学习**是一个多学科混合的领域，横跨计算机科学、工程技术和统计学等。要进行**机器学习**，必须要满足两个基本的条件：

1. 有大量的数据
2. 可以从大量的数据中获取到有用的信息

那么具体该怎么去做？稍后会进行学习。

总结一下，**机器学习**的真实含义：就是利用计算机技术来挖掘数据背后的真实含义，从而能够为人类提供帮助。


## 1.2 机器学习的应用场景

**机器学习**已经应用于多个领域。

* 搜索引擎：根据你的历史搜索点击，优化你下次的搜索结果；
* 垃圾邮件：自动过滤垃圾广告邮件到垃圾箱；
* 广告投放：会自动根据用户的喜好，投放其最为感兴趣的广告；
* 图像识别：自动识别出图像中的内容，例如车牌识别等；
* 信贷业务：会根据你的历史金融活动信息进行综合评估，决定是否有风险等。

那么在进行下面的内容前，我们需要了解几个概念：

1. 模式识别（Pattern Recognition）：是比较古老的一种技术，把环境和客体统称为“模式”，识别是对模式的一种认知，是如何让一个计算机程序去做一些看起来很“智能”的事情。

2. 机器学习（Machine Learning）：当下比较流行的技术，也是AI中最为基础的。**机器学习**强调的是，在给计算机程序或者机器输入一些数据后，程序或者机器开始学习这些数据，并且这个学习的步骤是明确的。 机器学习（Machine Learning）是一门专门研究计算机怎样模拟或实现人类的学习行为，以获取新的知识或技能，重新组织已有的知识结构使之不断改善自身性能的学科。

3. 深度学习（Deep Learning）：深度学习是非常崭新和有影响力的前沿领域。深度学习是机器学习研究中的一个新的领域，其动机在于建立、模拟人脑进行分析学习的神经网络，它模仿人脑的机制来解释数据，例如图像，声音和文本。


## 1.3 机器学习的主要任务

1. 分类：将实例数据划分到合适的分类中；
2. 回归：预测数值型数据，例如通过给定数据点来拟合最优曲线。

## 1.4 机器学习的分类

**机器学习**通常情况下分为两大类：

1. **监督学习**：
    * 必须确定目标变量的值，以便机器学习算法能够发现特征数据和目标变量之间的关系。（着包括分类任务和回归任务）
    * 样本集：训练集 + 测试集
        * 训练样本 = 特征（feature）+ 目标变量（label：分类--离散值/回归--连续值）
        * 特征通常是训练样本的列，它们是独立测量得到的
        * 目标变量：目标变量是机器学习算法的测试结果
            * 在分类算法中，目标变量的类型通常是标称型（例如：True/False），在回归算法中，目标变量通常是连续型（例如：0.0~100.0）
    * 知识表示：
        * 可以采用规则集的形式（例如：数学成绩大于90分的为优秀）
        * 可以采用概率分布的形式（例如：通过统计分布发现，90%的同学数学成绩在70分以下，那么大于70分的定为优秀）
        * 可以使用训练样本集中的一个实例（例如：通过样本集合，我们训练出了一个模型实例，得到某学生数学成绩好、比较积极等，我们认为是优秀）

2. **无监督学习**

    * 数据本身没有类别信息，也不会给定目标变量值。
    * 聚类：在无监督学习中，如果要将数据分成由类似的对象组成多个类的话，使用聚类。
    * 密度估计：将寻找描述数据统计值的过程称为密度估计（例如：根据训练样本确定特征1的概率分布）。
    * 无监督学习可以减少数据特征的维度，能够更好的使用二维或者三维的图形展示数据信息。


**机器学习**的**训练过程**一般如下图所示：

![](images/training-process.jpg)

下图列出了机器学习的主要任务，以及解决相应问题的算法汇总：

![](images/ml_algorithm.jpg)

## 1.5 如何选择合适的算法

选择机器学习算法前，需要考虑两个问题：

1. 使用机器学习算法的目的，想要算法完成何种任务？
    * 预测明天是否下雨。（因为可以使用历史天气情况进行预测，所以选择监督学习算法）
    * 给一群陌生人分组，但是并没有这些人的类别信息。（因为不知道具体的类别信息，因此选择无监督学习算法，通过他们的个体特征，例如身高、体重等特征进行处理）

2. 需要收集和分析的数据是什么？
    
 再确定了使用机器学习算法的目的之后，接下来就需要考虑数据问题。
 
 * 特征值是离散型的还是连续型的？
 * 特征值中是否存在缺失的值？如果有缺失，是何种原因造成了缺失？
 * 数据中是否存在异常值？
 * 某个特征发生的频率如何？（是否罕见的如海底捞针）等等

![](images/algorithm_selected.jpg)

## 1.6 开发机器学习应用程序的步骤


1. 收集数据：收集样本数据
2. 准备数据：准备数据格式
3. 分析数据：
    * 确保数据中没有垃圾数据
    * 如果是算法可以处理的数据格式或者可信任的数据源，可跳过此步骤
    * 需要人工干预，一定程度上降低了自动化价值
4. 训练算法：[机器学习算法核心] 如果使用无监督学习算法啊，由于不存在目标变量，可跳过此步骤
5. 测试算法：[机器学习算法核心] 评估算法效果
6. 使用算法：将机器学习算法转为应用程序

## 1.7 Python 语言的优势


1. 可以执行伪代码
2. 使用广泛，代码示例较多，模块库丰富
3. 语言简洁清晰，易于理解
4. 唯一的不足是性能问题
5. 机器学习常用的Python库：
    * 科学函数库： SciPy、Numpy
    * 绘图工具库：Matplotlib

# Numpy 函数库基础

Numpy是Python开发环境中的一个独立模块，是进行科学运算非常好的库，机器学习中涉及到的线性代数等运算，Numpy都可以直接使用。


In [2]:
# 引入Numpy类库
import numpy as np

In [5]:
# 构造 4 x 4 的随机数组
randArr = np.random.rand(4, 4)
randArr

array([[ 0.88925037,  0.31298575,  0.57548039,  0.55125056],
       [ 0.74900014,  0.06753901,  0.75000757,  0.83535517],
       [ 0.15018694,  0.63331357,  0.55510783,  0.14075455],
       [ 0.5929179 ,  0.30565914,  0.70585769,  0.7702969 ]])

In [6]:
# 数组转化为矩阵
randMat = np.mat(randArr)
randMat

matrix([[ 0.88925037,  0.31298575,  0.57548039,  0.55125056],
        [ 0.74900014,  0.06753901,  0.75000757,  0.83535517],
        [ 0.15018694,  0.63331357,  0.55510783,  0.14075455],
        [ 0.5929179 ,  0.30565914,  0.70585769,  0.7702969 ]])

In [8]:
# 矩阵求逆
invRandMat = randMat.I
invRandMat

matrix([[ 2.18554258, -0.00972236, -0.36113959, -1.48751463],
        [ 0.96716044, -4.11991392, -0.30918631,  3.83224059],
        [-1.52524656,  5.58399502,  2.80116417, -5.475944  ],
        [-0.66839389, -3.47457183, -2.16616674,  5.94037426]])

In [13]:
# 矩阵乘法
myEye = randMat * invRandMat
# 这里得到的结果应该是单位矩阵，除了对角线为1外，其他元素都是0，实际运算结果可能有出入，
# 这是因为计算机处理误差产生的结果
myEye

matrix([[  1.00000000e+00,  -4.44089210e-16,   0.00000000e+00,
          -8.88178420e-16],
        [  5.55111512e-17,   1.00000000e+00,  -2.22044605e-16,
          -8.88178420e-16],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   4.44089210e-16,   0.00000000e+00,
           1.00000000e+00]])

In [14]:
# 得到上述运算的误差值
myEye - np.eye(4)

matrix([[ -2.22044605e-16,  -4.44089210e-16,   0.00000000e+00,
          -8.88178420e-16],
        [  5.55111512e-17,   4.44089210e-16,  -2.22044605e-16,
          -8.88178420e-16],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   4.44089210e-16,   0.00000000e+00,
           0.00000000e+00]])